# raw ============================
raw_names <- c('Abies_arizonica',
                 'Abies_concolor',
                 'Acer_glabrum',
                 'Achillea_millefolium',
                 'Achnatherum_sp_1',
                 'Aconitum_columbianum',
                 'Actea_rubra',
                 'Agonis',
                 'Agoseris_glauca',
                 'Agrostis_scabra',
                 'Agrostis_stolonifera',
                 'Agrostis_stotonifera',
                 'Allium_cernuum',
                 'Allium_geyeri',
                 'Alnus_incana',
                 'Androsace_septentironalus',
                 'Androsace_septentrionalis',
                 'Antennaria_microphylla',
                 'Antennaria_neglecta',
                 'Antennaria_parvifolia',
                 'Aquilegia_sp',
                 'Arctostaphylos_uva_ursi',
                 'Arenaria_fendleri',
                 'Arenaria_lanuganosa',
                 'Artemisia_caruthii',
                 'Artemisia_dracunculus',
                 'Artemisia_franseroides',
                 'Artemisia_frigida', 'Artemisia_ludoviciana', 'Asteraceae',
                 'Astragalus', 'Astragalus_laxmannii_var_robustior',
                 'Astragalus_sp26', 'Athyrium_filix_femina',
                 'Axyris_amaranthoides', 'Berula_erecta', 'Blitum_capitatum',
                 'Boechera_drummondii', 'Boechera_pendulina', 'Bouteloua_gracilis',
                 'Brassicaceae_sp', 'Brickellia_grandiflora', 'Bromus_ciliatus',
                 'Bromus_intermis', 'Bromus_porteri', 'Bromus_pumpellianus',
                 'Bromus_secalinus', 'Bromus_sp', 'Calamagrostis_sp',
                 'Calamagrostis_stricta', 'Calochortus_gunnisonii',
                 'Campanula_rotundifolia', 'Cardamine_cordifolia',
                 'Carex_douglasii', 'Carex_geyeri', 'Carex_microptera',
                 'Carex_occidentalis', 'Carex_optusata', 'Carex_pedisata',
                 'Carex_praegracilis', 'Carex_rossii', 'Carex_secada', 'Carex_sp',
                 'Carex_sp1', 'Carex_sp2', 'Cerastium_arvense', 'Cercocarpus_montanus',
                 'cf_Aquilegia_sp', 'cf_Aquilegia_sp_2', 'cf_Asteraceae_sp',
                 'cf_Cornus_sp', 'cf_Liliaceae_sp', 'cf_Phrymaceae_sp',
                 'cf_Salix_sp', 'Chaemerion_angustifolium', 'Chenopodium_atrovirens',
                 'Chenopodium_fremontii', 'Cirsium_pallidum', 'Conioselenum_scopulorum',
                 'Corydalis_aurea', 'Cyperaceae_sp', 'Cystepteris_revisiana',
                 'Danthonea_intermedia', 'Danthonea_parryi', 'Danthonia_parryi',
                 'Dasiphora_fruticosa', 'Dasyphora_fruticosa', 'Deschampsia_caespitosa',
                 'Draba_sp', 'Draba_sp24', 'Drymocallis_fissa', 'Dryopteris_filis_mas',
                 'Elymus_elymoides', 'Elymus_glauca', 'Elymus_glaucus', 'Elymus_repens',
                 'Elymus_sp', 'Elymus_trachycaulus', 'Epilobium_sp', 'Eremogone_fendleri',
                 'Eremogone_hookeri', 'Erigeron_canadensis', 'Erigeron_compositius',
                 'Erigeron_compositus', 'Erigeron_divergens', 'Erigeron_eximius',
                 'Erigeron_flagellaris', 'Erigeron_formosissimus', 'Erigeron_glabellus',
                 'Erigeron_sp', 'Erigeron_sp_24', 'Erigeron_sp21', 'Erigeron_speciosus',
                 'Erigeron_vetensis', 'Erythranthe_guttata', 'Fern_sp',
                 'Festuca_arizonica', 'Festuca_calligera', 'Festuca_sororia',
                 'Festuca_thurberi', 'Fragaria_sp', 'Fragaria_vesca',
                 'Fragaria_virginiana', 'Frageria_vesca', 'Galium_boreale',
                 'Gallium_boreale', 'Gallium_mexicana', 'Gallium_mexicanum',
                 'Gentianella_amarilla', 'Geranium_caespitosum',
                 'Geranium_richardsonii', 'Geranium_viscosissimum_var_incisum',
                 'Geum_macrophyllum', 'Geum_triflorum', 'Glyceria_borealis',
                 'Goodyera_repens', 'Heliomeris_multiflora', 'Heracleum_maximum',
                 'Heterotheca_foliosa', 'Heterotheca_villosa', 'Heuchera_parvifolia',
                 'Holodiscus_discolor', 'Hydrophyllum_fendleri', 'Hymenoxis_hoopesii',
                 'Ipomopsis_aggregata', 'Iris_missouriensis', 'Jamesia_americana',
                 'Juncus_balticus', 'Juncus_encifolius', 'Juniperus_communis',
                 'Juniperus_horizontalis', 'Juniperus_scopulorum',
                 'Keoleria_macrantha', 'Koeleria_macrantha',
                 'Laennecia_schiedeana', 'Lamiaceae_sp', 'Lathyrus_lanzwertii',
                 'Lepidium_virginicum', 'Lomatium_linearifolium', 'Luzula_parviflora',
                 'Mahonia_repens', 'Maianthemum_stellaria', 'Maianthemum_stellatum',
                 'MEF11_1', 'MEF11_2', 'MEF2_1', 'Mertensia_ciliata', 'Mertensia_franciscona',
                 'Mertensia_fransiscana', 'Mertensia_lanceolata', 'Micranthes_edontiloma',
                 'Mirabalis_alba', 'Monocot_sp21', 'Muhlenbergia_montana',
                 'Muhlenbergia_richardsonii', 'Muhlenbergia_tricholepsis',
                 'Muhlenbergia_wrightii', 'Nasturtium_officinale', 'Oreochrysum_parryi',
               'Orthilia_secunda', 'Orthocarpus_lutea', 'Oxalis_violacea', 'Oxypolis_fendleri',
               'Packera_fendleri', 'Packera_multilobata', 'Pascopyrum_smithii',
               'Paxistema_myrsinites', 'Penstemon_rydbergii', 'Penstemon_sp',
               'Penstemon_sp1', 'Penstemon_whippleanus', 'Phacelia_heterophylla',
               'Phleum_alpinum', 'Phleum_pratense', 'Picea_englemanii',
               'Picea_pungens', 'Pinus_flexilis', 'Pinus_ponderosa',
               'Pinus_reflexa', 'Poa_fendleriana', 'Poa_pratensis', 'Poa_sp',
               'Poaceae_sp', 'Populus_tremuloides', 'Potentilla_anserina',
               'Potentilla_hipiana', 'Potentilla_hippiana', 'Potentilla_pulcherrima',
               'Potentilla_rupincola', 'Potintilla_diversifolia',
               'Primula_pauciflora_var_pauciflora', 'Pseudocymopteris_montanum',
               'Pseudotsuga_menziesii', 'Ranunculaceae_sp', 'Ranunculaceae_sp22',
               'Ranunculus_cardiophyla', 'Ribes_cereum', 'Ribes_montigenum',
               'Ribes_sp', 'Robinia_neomexicana', 'Rosa_sp', 'Rosa_woodsii',
               'Rubus_deliciosus', 'Rubus_ideaus', 'Rubus_parviflora',
               'Rudbeckia_hirta', 'Rudbeckia_laciniata', 'Rumex_acetacella',
               'Sambucus_racemosa', 'Sedum_lanceolatum', 'Senecio_bigelovii',
               'Senecio_eremophilus', 'Senecio_pudicus', 'Senecio_wootonii',
               'Silene_scouleri', 'Silene_sp26', 'Sisymbrium_sp',
               'Sisyrancheum_montanum', 'Solidago_missouriensis',
               'Solidago_sp', 'Stellaria_sp', 'Straptopus_amphlexifolius',
               'Symphiotrichum_ascendens', 'Symphoricarpos_rotundifolius',
               'Symphoricarpos_sp', 'Symphyotrichum_falcatum',
               'Synthyris_plantaginea', 'Taraxacum_officinale',
               'Taxistema_mysirites', 'Thalictrum_fendleri', 'Thermopsis_montana',
               'Tragopogon_dubius', 'Trifolium_longipes', 'Trifolium_pratense',
               'Trifolium_repens', 'Unk_25', 'Urtica_dioica', 'Vaccinium_myrtilius',
               'Vaccinium_scoparium', 'Veratrum_californicum', 'Verbascum_thapsis',
               'Veronica_plantaginea', 'Veronica_sp', 'Vicia_americana',
               'Viola_canadensis', 'Viola_necrophylla', 'Woodsia_oregana', 'Xanthisma_coloradoense')
# corrected =====================
corrected_names <- c('Abies_arizonica',
               'Abies_concolor',
               'Acer_glabrum',
               'Achillea_millefolium',
               'Achnatherum_sp_1',
               'Aconitum_columbianum',
               'Actea_rubra',
               'Agonis',
               'Agoseris_glauca',
               'Agrostis_scabra',
               'Agrostis_stolonifera',
               'Agrostis_stotonifera',
               'Allium_cernuum',
               'Allium_geyeri',
               'Alnus_incana',
               'Androsace_septentironalus',
               'Androsace_septentrionalis',
               'Antennaria_microphylla',
               'Antennaria_neglecta',
               'Antennaria_parvifolia',
               'Aquilegia_sp',
               'Arctostaphylos_uva_ursi',
               'Arenaria_fendleri',
               'Arenaria_lanuganosa',
               'Artemisia_caruthii',
               'Artemisia_dracunculus',
               'Artemisia_franseroides',
               'Artemisia_frigida', 'Artemisia_ludoviciana', 'Asteraceae',
               'Astragalus', 'Astragalus_laxmannii_var_robustior',
               'Astragalus_sp26', 'Athyrium_filix_femina',
               'Axyris_amaranthoides', 'Berula_erecta', 'Blitum_capitatum',
               'Boechera_drummondii', 'Boechera_pendulina', 'Bouteloua_gracilis',
               'Brassicaceae_sp', 'Brickellia_grandiflora', 'Bromus_ciliatus',
               'Bromus_intermis', 'Bromus_porteri', 'Bromus_pumpellianus',
               'Bromus_secalinus', 'Bromus_sp', 'Calamagrostis_sp',
               'Calamagrostis_stricta', 'Calochortus_gunnisonii',
               'Campanula_rotundifolia', 'Cardamine_cordifolia',
               'Carex_douglasii', 'Carex_geyeri', 'Carex_microptera',
               'Carex_occidentalis', 'Carex_optusata', 'Carex_pedisata',
               'Carex_praegracilis', 'Carex_rossii', 'Carex_secada', 'Carex_sp',
               'Carex_sp1', 'Carex_sp2', 'Cerastium_arvense', 'Cercocarpus_montanus',
               'cf_Aquilegia_sp', 'cf_Aquilegia_sp_2', 'cf_Asteraceae_sp',
               'cf_Cornus_sp', 'cf_Liliaceae_sp', 'cf_Phrymaceae_sp',
               'cf_Salix_sp', 'Chaemerion_angustifolium', 'Chenopodium_atrovirens',
               'Chenopodium_fremontii', 'Cirsium_pallidum', 'Conioselenum_scopulorum',
               'Corydalis_aurea', 'Cyperaceae_sp', 'Cystepteris_revisiana',
               'Danthonea_intermedia', 'Danthonea_parryi', 'Danthonia_parryi',
               'Dasiphora_fruticosa', 'Dasyphora_fruticosa', 'Deschampsia_caespitosa',
               'Draba_sp', 'Draba_sp24', 'Drymocallis_fissa', 'Dryopteris_filis_mas',
               'Elymus_elymoides', 'Elymus_glauca', 'Elymus_glaucus', 'Elymus_repens',
               'Elymus_sp', 'Elymus_trachycaulus', 'Epilobium_sp', 'Eremogone_fendleri',
               'Eremogone_hookeri', 'Erigeron_canadensis', 'Erigeron_compositius',
               'Erigeron_compositus', 'Erigeron_divergens', 'Erigeron_eximius',
               'Erigeron_flagellaris', 'Erigeron_formosissimus', 'Erigeron_glabellus',
               'Erigeron_sp', 'Erigeron_sp_24', 'Erigeron_sp21', 'Erigeron_speciosus',
               'Erigeron_vetensis', 'Erythranthe_guttata', 'Fern_sp',
               'Festuca_arizonica', 'Festuca_calligera', 'Festuca_sororia',
               'Festuca_thurberi', 'Fragaria_sp', 'Fragaria_vesca',
               'Fragaria_virginiana', 'Frageria_vesca', 'Galium_boreale',
               'Gallium_boreale', 'Gallium_mexicana', 'Gallium_mexicanum',
               'Gentianella_amarilla', 'Geranium_caespitosum',
               'Geranium_richardsonii', 'Geranium_viscosissimum_var_incisum',
               'Geum_macrophyllum', 'Geum_triflorum', 'Glyceria_borealis',
               'Goodyera_repens', 'Heliomeris_multiflora', 'Heracleum_maximum',
               'Heterotheca_foliosa', 'Heterotheca_villosa', 'Heuchera_parvifolia',
               'Holodiscus_discolor', 'Hydrophyllum_fendleri', 'Hymenoxis_hoopesii',
               'Ipomopsis_aggregata', 'Iris_missouriensis', 'Jamesia_americana',
               'Juncus_balticus', 'Juncus_encifolius', 'Juniperus_communis',
               'Juniperus_horizontalis', 'Juniperus_scopulorum',
               'Keoleria_macrantha', 'Koeleria_macrantha',
               'Laennecia_schiedeana', 'Lamiaceae_sp', 'Lathyrus_lanzwertii',
               'Lepidium_virginicum', 'Lomatium_linearifolium', 'Luzula_parviflora',
               'Mahonia_repens', 'Maianthemum_stellaria', 'Maianthemum_stellatum',
               'MEF11_1', 'MEF11_2', 'MEF2_1', 'Mertensia_ciliata', 'Mertensia_franciscona',
               'Mertensia_fransiscana', 'Mertensia_lanceolata', 'Micranthes_edontiloma',
               'Mirabalis_alba', 'Monocot_sp21', 'Muhlenbergia_montana',
               'Muhlenbergia_richardsonii', 'Muhlenbergia_tricholepsis',
               'Muhlenbergia_wrightii', 'Nasturtium_officinale', 'Oreochrysum_parryi',
               'Orthilia_secunda', 'Orthocarpus_lutea', 'Oxalis_violacea', 'Oxypolis_fendleri',
               'Packera_fendleri', 'Packera_multilobata', 'Pascopyrum_smithii',
               'Paxistema_myrsinites', 'Penstemon_rydbergii', 'Penstemon_sp',
               'Penstemon_sp1', 'Penstemon_whippleanus', 'Phacelia_heterophylla',
               'Phleum_alpinum', 'Phleum_pratense', 'Picea_englemanii',
               'Picea_pungens', 'Pinus_flexilis', 'Pinus_ponderosa',
               'Pinus_reflexa', 'Poa_fendleriana', 'Poa_pratensis', 'Poa_sp',
               'Poaceae_sp', 'Populus_tremuloides', 'Potentilla_anserina',
               'Potentilla_hipiana', 'Potentilla_hippiana', 'Potentilla_pulcherrima',
               'Potentilla_rupincola', 'Potintilla_diversifolia',
               'Primula_pauciflora_var_pauciflora', 'Pseudocymopteris_montanum',
               'Pseudotsuga_menziesii', 'Ranunculaceae_sp', 'Ranunculaceae_sp22',
               'Ranunculus_cardiophyla', 'Ribes_cereum', 'Ribes_montigenum',
               'Ribes_sp', 'Robinia_neomexicana', 'Rosa_sp', 'Rosa_woodsii',
               'Rubus_deliciosus', 'Rubus_ideaus', 'Rubus_parviflora',
               'Rudbeckia_hirta', 'Rudbeckia_laciniata', 'Rumex_acetacella',
               'Sambucus_racemosa', 'Sedum_lanceolatum', 'Senecio_bigelovii',
               'Senecio_eremophilus', 'Senecio_pudicus', 'Senecio_wootonii',
               'Silene_scouleri', 'Silene_sp26', 'Sisymbrium_sp',
               'Sisyrancheum_montanum', 'Solidago_missouriensis',
               'Solidago_sp', 'Stellaria_sp', 'Straptopus_amphlexifolius',
               'Symphiotrichum_ascendens', 'Symphoricarpos_rotundifolius',
               'Symphoricarpos_sp', 'Symphyotrichum_falcatum',
               'Synthyris_plantaginea', 'Taraxacum_officinale',
               'Taxistema_mysirites', 'Thalictrum_fendleri', 'Thermopsis_montana',
               'Tragopogon_dubius', 'Trifolium_longipes', 'Trifolium_pratense',
               'Trifolium_repens', 'Unk_25', 'Urtica_dioica', 'Vaccinium_myrtilius',
               'Vaccinium_scoparium', 'Veratrum_californicum', 'Verbascum_thapsis',
               'Veronica_plantaginea', 'Veronica_sp', 'Vicia_americana',
               'Viola_canadensis', 'Viola_necrophylla', 'Woodsia_oregana', 'Xanthisma_coloradoense')

