---
title: "Microclimate and its effect on vegetation in the Southern Rocky Mountains"
output: pdf_document
author: Adam L. Mahood
date: "2024-02-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# summarising climate data then relating to community composition
library(tidyverse)
library(topomicro)
library(vegan)
library(terra)
library(ggpubr)
library(sf)
library(ggrepel)
```

## Initial findings


```{r cars, include=FALSE, echo=F}

vall_veg <- readr::read_csv("data/valles_caldera/microclimate - VALL_veg.csv") |>
  dplyr::select(plot, species) |>
  dplyr::mutate(occurrence = 1,
                plot = str_to_lower(plot) %>% str_remove_all("_"),
                species = str_replace_all(species, " ", "_")|>
                  str_replace_all("-", "_")) |>
  tidyr::pivot_wider(names_from = species, values_from = occurrence,
                     values_fn = first, values_fill = 0) |>
  mutate(plot = ifelse(str_sub(plot, 3,3) == "0", str_remove_all(plot, "0"), plot)) |>
  filter(plot %in% rownames(vall_plotwise_summaries)) |>
  arrange(plot) %>%
  tibble::column_to_rownames("plot");vall_veg

vall_clim <- read_csv("data/cleaned_bm/vall_dec22.csv")

vall_plotwise_summaries <-
  vall_clim |>
  plotwise_summary()


```

## Map of sensor locations

```{r pressure, echo=FALSE}

```

## sensor time series measurements

```{r pressure, echo=FALSE}

```

## Plot of Minimum vpd vs Diurnal Temperature Range

```{r pressure, echo=FALSE}

```


## Non-metric multidimensional scaling plots

This illustrates how 

```{r pressure, echo=FALSE}

```


## Map of sensor locations

```{r pressure, echo=FALSE}

```

